language: java
notifications:
    webhooks:
        urls:
            - http://cs.worcester.edu/cgi-bin/cs-348/ci-cd-test/deploy.cgi
        on_success: always
        on_failure: never
        on_start: never